### ISSUE TITLE
I am using GROMACS as a molecular dynamics simulation tool and planning to use either MDAnalysis or mdtraj for analyzing collective variables. My question is whether these libraries support reading .xtc or .trr trajectory files generated from GROMACS simulations for identification of collective variables.

### ISSUE THREAD

**Issue by vishnu-thumpudi2108** [luigibonati/mlcolvar#125]
Details : - 
Simulation Tool: GROMACS
Analysis Library Options: MDAnalysis or mdtraj

Could you please provide information on:

Whether MlColvar libraries can directly handle .xtc or .trr files.
Any recommended approaches or examples for using these libraries to identify collective variables from GROMACS trajectories.
If support for .xtc or .trr files is not available, are there alternative methods or tools recommended for this purpose?
Additional Context
I have experience using GROMACS for molecular dynamics simulations and have successfully generated .xtc or .trr trajectory files. However, I am seeking guidance on how to leverage mlcolvar to identify collective variables such as principal components or other relevant features.

Any insights or recommendations would be greatly appreciated!

**Comment by EnricoTrizio** [comment]
> Whether MlColvar libraries can directly handle .xtc or .trr files.

No, it can't. You should either use Plumed (suggested) or something else to process them.
With plumed you can also analyze trajectories from files using the [driver command](https://www.plumed.org/doc-v2.8/user-doc/html/driver.html)
