### ISSUE TITLE
Link to documentation in README

### ISSUE THREAD

**Issue by recisic** [luigibonati/mlcolvar#141]
Ciao mlcolvar team,

Thanks for the useful package! I wanted to let you know that there is no link to the documentation in the `README.md` except for the docs status badge, so it's hard to find the documentation.

How about adding links to:
- The "documentation" and "examples" in the following part of the README
- **About** section on the right of the GitHub page

https://github.com/luigibonati/mlcolvar/blob/3f9adeb6d02e60161f44f06b413adcec76c216cd/README.md?plain=1#L34

Grazie mille,
Juno

**Comment by luigibonati** [comment]
Hi Juno! Thanks for the suggestion, I've added more explicit links to the doc

Ciao, 
Luigi
