### ISSUE TITLE
Bugfixes v1.1.1

### ISSUE THREAD

**Issue by luigibonati** [luigibonati/mlcolvar#144]
In order to fix the dependency issues between our current PyPI version (`mlcolvar=1.1.0`) and the latest pytorch one (`torch=2.3`) which were reported in (#143) I would do a patch version **v1.1.1** that:

- sets torch<2.3 as dependency
- fixes the other bug with the device and load_from_checkpoint tests (#117)

I ran the tests locally with a fresh environment, and with these two modifications, they work fine. I was wondering whether we should also keep a `stable` (corresponding to the PyPI version) branch on which to run the CI in order to immediately detect dependency issues like this. @andrrizzi, any thoughts on this?

**Comment by andrrizzi** [comment]
> I was wondering whether we should also keep a stable (corresponding to the PyPI version) branch on which to run the CI in order to immediately detect dependency issues like this.

That sounds like a good idea to me. The disadvantage would be that we'll have to apply bugfixes twice (in ``main`` and ``stable``) when we find them.

An alternative could be add a separate nightly CI workflow to test the pypi installation, which shouldn't require maintaining a ``stable`` branch, and avoids running the entire test suite of the stable version every time.

**Comment by luigibonati** [comment]
I agree with your suggestion, I am working on it in #146 to add a new CI workflow! thank you

**Comment by luigibonati** [comment]
In any case
