### ISSUE TITLE
make nomenclature pep8 compliant

### ISSUE THREAD

**Issue by luigibonati** [luigibonati/mlcolvar#39]
Some things that @andrrizzi suggested to clean up:

Breaking changes:
- [x] CV names: Xyz_CV --> XyzCV
- [x] normIn --> norm_in (in cvs blocks) 
- [x] MSE_loss --> mse_loss
- [x] TDA_loss --> tda_loss

Internal changes:
- [x] TICA member: (reg_c0 -> reg_C_0)
- [x] Normalization: members ('Mean','Range')
- [x] Statistics: members ('Mean','Std','Min','Max')
- [x] Transforms: check all

**Comment by luigibonati** [comment]
I did all the changes but for the first and the last one. 

- Regarding CVs' names: DeepLDACV, DeepTICACV, DeepTDACV looks ugly to me due to the too many capital letters, while the others (like RegressionCV or AutoEncoderCV are betters). Should we make an exception / think about a different notation?
- Regarding the transforms that @EnricoTrizio added I did not change them (we might want to understand which of them  we want to add in the first version)

**Comment by andrrizzi** [comment]
Thanks!

For the CV name, I'd still follow PEP8 nomenclature conventions (it probably just takes a bit of getting used to). Alternatively, we could just drop ``CV`` from their name (or for a subset of CVs). If we really want to emphasize in the tutorial that they are CVs, we could also use the package for that. For example
```python
from mlcvs import cvs
cv = cvs.DeepLDA(...)
```
