### ISSUE TITLE
[docs] add notebooks

### ISSUE THREAD

**Issue by luigibonati** [luigibonati/mlcolvar#9]
## Introduction

- [x] Getting started
- [x] Creating datasets
- [x] Customize loss and optimizer

## NN-based CVs

- [x] Autoencoder
- [x] Deep-LDA
- [x] Deep-TDA
- [x] Deep-TICA

## Linear models

- [x] LDA
- [x] TICA

## Customize 

- [x] Multitask
- [x] Preprocessing 
- [x] Adding a new cv from scratch
- [x] Adding a new CV by overload

**Comment by EnricoTrizio** [comment]
Completed in #62 and #77
