### ISSUE TITLE
Problems in compiling torch module in plumed

### ISSUE THREAD

**Issue by JinyinZha** [luigibonati/mlcolvar#90]
Pytorch==1.13.1

In the beginning, I start to compile the torch module of plumed with libtorch-cxx11-abi-shared-with-deps-1.13.1+cpu, then I found the error "undefined reference to ‘powf@GLIBC_2.27'".

As it is not wise to update GLIBC, I then try to use libtorch-1.13.1 without ABI, then another error occurred: 

> 
    """collect2: error: ld returned 1 exit status
        Makefile:499: recipe for target 'plumed' failed
        make[4]: *** [plumed] Error 1
        make[4]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0/src/lib'
        Makefile:110: recipe for target 'all' failed
        make[3]: *** [all] Error 2
        make[3]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0/src/lib'
        Makefile:8: recipe for target 'lib' failed
        make[2]: *** [lib] Error 2
        make[2]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0/src'
        Makefile:33: recipe for target 'lib' failed
        make[1]: *** [lib] Error 2
        make[1]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0'
        Makefile:21: recipe for target 'all' failed
        make: *** [all] Error 2"""

In fact, I have tried to install GLIBC-2.27 in my own path. However, it throws out a weird error:

> 

    """make -r PARALLELMFLAGS="" -C .. objdir=`pwd` all
        make[1]: Entering directory `/home/jyzha/tmp/glibc-2.27'
        make  subdir=csu -C csu ..=../ subdir_lib
        make[2]: Entering directory `/home/jyzha/tmp/glibc-2.27/csu'
        /usr/bin/install -c -m 644  /home/jyzha/tmp/glibc-2.27/build/cstdlibT
        /usr/bin/install: missing destination file operand after ‘/home/jyzha/tmp/glibc-2.27/build/cstdlibT’
        Try '/usr/bin/install --help' for more information."""

 I am looking forward to your advice on installing the torch module. I strongly require this tool in my work and I am also willing to contribute to mlcolvar.  Thank you~

**Comment by EnricoTrizio** [comment]
Hi Jinyin,
First, sorry for the late reply.

About your issue, with those few details, it's difficult to help! 
You did not provide many important details for debugging.

Can you please give more information about:
1. Where are you trying to install the code (workstation, cluster..) and what OS are you using?
2. The error lines you get, i.e., from which command they are triggered and the actual error (not the make _leaving_ messages) You can find these things in the config.log file in PLUMED installation folder
3. The configuration option you are using, i.e. the configure command you are using for PLUMED
4. Some details on the steps you have followed for the installation, i.e., which version of PLUMED, if you followed the instructions on PLUMED website, if you exported the libtorch path etc.

Hopefully with more details we can help you

**Comment by JinyinZha** [comment]
Thanks for the reply.
I compile plumed on centos 7.9, using the commands from the [tutorial](https://www.plumed.org/doc-v2.9/user-doc/html/_p_y_t_o_r_c_h.html)
`./configure --enable-libtorch --enable-modules=pytorch --prefix=/home/jyzha/software/plumed-2.9 `
The configuration is OK. It shows
`checking whether mpic++ accepts -std=c++14... yes
checking libtorch without extra libs... no
checking libtorch with  -ltorch_cpu -lc10... yes`
Then I start to compile.
`make -j32`
Then the error "undefined reference to ‘powf@GLIBC_2.27'" is thrown. It seems to be the problem of GLIBC. As it is not wise to update GLIBC, I then try to use libtorch-1.13.1 without ABI, then another error occurred:
`collect2: error: ld returned 1 exit status
    Makefile:499: recipe for target 'plumed' failed
    make[4]: *** [plumed] Error 1
    make[4]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0/src/lib'
    Makefile:110: recipe for target 'all' failed
    make[3]: *** [all] Error 2
    make[3]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0/src/lib'
    Makefile:8: recipe for target 'lib' failed
    make[2]: *** [lib] Error 2
    make[2]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0/src'
    Makefile:33: recipe for target 'lib' failed
    make[1]: *** [lib] Error 2
    make[1]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0'
    Makefile:21: recipe for target 'all' failed
    make: *** [all] Error 2`
Therefore, I tried to update my GLIBC (2.27) in my own account, and it still fails in the make step. 
`wget https://ftp.gnu.org/gnu/glibc/glibc-2.28.tar.gz
tar -xvf glibc-2.27.tar.gz
cd glibc-2.27
mkdir build 
cd build
…/configure --prefix=/home/jyzha/software/glibc-2.27
make -j32`
And it also fails.
`"make -r PARALLELMFLAGS="" -C .. objdir=`pwd` all
    make[1]: Entering directory `/home/jyzha/tmp/glibc-2.27'
    make  subdir=csu -C csu ..=../ subdir_lib
    make[2]: Entering directory `/home/jyzha/tmp/glibc-2.27/csu'
    /usr/bin/install -c -m 644  /home/jyzha/tmp/glibc-2.27/build/cstdlibT
    /usr/bin/install: missing destination file operand after ‘/home/jyzha/tmp/glibc-2.27/build/cstdlibT’
    Try '/usr/bin/install --help' for more information.`

**Comment by JinyinZha** [comment]
> Thanks for the reply. I compile plumed on centos 7.9, using the commands from the [tutorial](https://www.plumed.org/doc-v2.9/user-doc/html/_p_y_t_o_r_c_h.html)
> 
> `./configure --enable-libtorch --enable-modules=pytorch --prefix=/home/jyzha/software/plumed-2.9 `
> 
> The configuration is OK. It shows
> 
> `checking whether mpic++ accepts -std=c++14... yes
> 
> checking libtorch without extra libs... no
> 
> checking libtorch with -ltorch_cpu -lc10... yes`
> 
> Then I start to compile.
> 
> `make -j32`
> 
> Then the error "undefined reference to ‘powf@GLIBC_2.27'" is thrown. It seems to be the problem of GLIBC. As it is not wise to update GLIBC, I then try to use libtorch-1.13.1 without ABI, then another error occurred:
> 
> `collect2: error: ld returned 1 exit status
> 
> ```
> Makefile:499: recipe for target 'plumed' failed
> 
> make[4]: *** [plumed] Error 1
> 
> make[4]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0/src/lib'
> 
> Makefile:110: recipe for target 'all' failed
> 
> make[3]: *** [all] Error 2
> 
> make[3]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0/src/lib'
> 
> Makefile:8: recipe for target 'lib' failed
> 
> make[2]: *** [lib] Error 2
> 
> make[2]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0/src'
> 
> Makefile:33: recipe for target 'lib' failed
> 
> make[1]: *** [lib] Error 2
> 
> make[1]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0'
> 
> Makefile:21: recipe for target 'all' failed
> 
> make: *** [all] Error 2`
> ```
> 
> Therefore, I tried to update my GLIBC (2.27) in my own account, and it still fails in the make step.
> 
> `wget https://ftp.gnu.org/gnu/glibc/glibc-2.28.tar.gz
> 
> tar -xvf glibc-2.27.tar.gz
> 
> cd glibc-2.27
> 
> mkdir build
> 
> cd build
> 
> …/configure --prefix=/home/jyzha/software/glibc-2.27
> 
> make -j32`
> 
> And it also fails.
> 
> `"make -r PARALLELMFLAGS="" -C .. objdir=`pwd` all
> 
> ```
> make[1]: Entering directory `/home/jyzha/tmp/glibc-2.27'
> 
> make  subdir=csu -C csu ..=../ subdir_lib
> 
> make[2]: Entering directory `/home/jyzha/tmp/glibc-2.27/csu'
> 
> /usr/bin/install -c -m 644  /home/jyzha/tmp/glibc-2.27/build/cstdlibT
> 
> /usr/bin/install: missing destination file operand after ‘/home/jyzha/tmp/glibc-2.27/build/cstdlibT’
> 
> Try '/usr/bin/install --help' for more information.`
> ```

**Comment by JinyinZha** [comment]
> Hi Jinyin, First, sorry for the late reply.
> 
> About your issue, with those few details, it's difficult to help! You did not provide many important details for debugging.
> 
> Can you please give more information about:
> 
>     1. Where are you trying to install the code (workstation, cluster..) and what OS are you using?
> 
>     2. The error lines you get, i.e., from which command they are triggered and the actual error (not the make _leaving_ messages) You can find these things in the config.log file in PLUMED installation folder
> 
>     3. The configuration option you are using, i.e. the configure command you are using for PLUMED
> 
>     4. Some details on the steps you have followed for the installation, i.e., which version of PLUMED, if you followed the instructions on PLUMED website, if you exported the libtorch path etc.
> 
> 
> Hopefully with more details we can help you

> Thanks for the reply. I compile plumed on centos 7.9, using the commands from the [tutorial](https://www.plumed.org/doc-v2.9/user-doc/html/_p_y_t_o_r_c_h.html)
> 
> `./configure --enable-libtorch --enable-modules=pytorch --prefix=/home/jyzha/software/plumed-2.9 `
> 
> The configuration is OK. It shows
> 
> `checking whether mpic++ accepts -std=c++14... yes
> 
> checking libtorch without extra libs... no
> 
> checking libtorch with -ltorch_cpu -lc10... yes`
> 
> Then I start to compile.
> 
> `make -j32`
> 
> Then the error "undefined reference to ‘powf@GLIBC_2.27'" is thrown. It seems to be the problem of GLIBC. As it is not wise to update GLIBC, I then try to use libtorch-1.13.1 without ABI, then another error occurred:
> 
> `collect2: error: ld returned 1 exit status
> 
> ```
> Makefile:499: recipe for target 'plumed' failed
> 
> make[4]: *** [plumed] Error 1
> 
> make[4]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0/src/lib'
> 
> Makefile:110: recipe for target 'all' failed
> 
> make[3]: *** [all] Error 2
> 
> make[3]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0/src/lib'
> 
> Makefile:8: recipe for target 'lib' failed
> 
> make[2]: *** [lib] Error 2
> 
> make[2]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0/src'
> 
> Makefile:33: recipe for target 'lib' failed
> 
> make[1]: *** [lib] Error 2
> 
> make[1]: Leaving directory '/home/jyzha/tmp/plumed-2.9.0'
> 
> Makefile:21: recipe for target 'all' failed
> 
> make: *** [all] Error 2`
> ```
> 
> Therefore, I tried to update my GLIBC (2.27) in my own account, and it still fails in the make step.
> 
> `wget https://ftp.gnu.org/gnu/glibc/glibc-2.28.tar.gz
> 
> tar -xvf glibc-2.27.tar.gz
> 
> cd glibc-2.27
> 
> mkdir build
> 
> cd build
> 
> …/configure --prefix=/home/jyzha/software/glibc-2.27
> 
> make -j32`
> 
> And it also fails.
> 
> `"make -r PARALLELMFLAGS="" -C .. objdir=`pwd` all
> 
> ```
> make[1]: Entering directory `/home/jyzha/tmp/glibc-2.27'
> 
> make  subdir=csu -C csu ..=../ subdir_lib
> 
> make[2]: Entering directory `/home/jyzha/tmp/glibc-2.27/csu'
> 
> /usr/bin/install -c -m 644  /home/jyzha/tmp/glibc-2.27/build/cstdlibT
> 
> /usr/bin/install: missing destination file operand after ‘/home/jyzha/tmp/glibc-2.27/build/cstdlibT’
> 
> Try '/usr/bin/install --help' for more information.`
> ```

**Comment by EnricoTrizio** [comment]
Ciao, I had a chat with @luigibonati and this reminded him of a similar problem someone else encountered in the past.
In that case, the solution was to compile libtorch from scratch.

I'll leave you the link to the discussion thread from PLUMED users group so you can try to follow it and hopefully solve the problem:

https://groups.google.com/g/plumed-users/c/F_59ozWJh1s/m/CkYgVl0UEAAJ?pli=1

Let us know if this helps!

**Comment by JinyinZha** [comment]
Much thanks, I would try it.

**Comment by EnricoTrizio** [comment]
Since this issue has been inactive for a long time, I'll close it for now, hoping the problem was solved :smile:
